version: "3.9"
services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file: ./.env
    command: npm run dev
  database:
    image: "mongo"
    env_file: ./.env
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
